# Generated by Django 5.1 on 2024-10-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartaoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartao',
            name='id_agencia',
        ),
        migrations.RemoveField(
            model_name='cartao',
            name='id_funcao',
        ),
        migrations.DeleteModel(
            name='Agencia',
        ),
        migrations.DeleteModel(
            name='Cartao',
        ),
        migrations.DeleteModel(
            name='Funcao',
        ),
    ]
